# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=RootPassword@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=MyEcommercePlatformJwtSecretKeyForAuthentication2026SecureKeyMustBeLongEnough!!
jwt.expiration=86400000

# Port should be 8080
server.port=8080